CREATE TABLE IF NOT EXISTS events (
       id BIGSERIAL PRIMARY KEY,
       type VARCHAR(50) NOT NULL,
       data TEXT,
       date_created TIMESTAMP NOT NULL
);

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO processit;
GRANT SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA public
TO processit;
